{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import multiprocessing\n",
    "import numpy as np\n",
    "from PIL import Image\n",
    "import uuid\n",
    "import time"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "def delabeler(path_tuple):\n",
    "    '''\n",
    "    Takes a tuple which consists of original RGB image and the labelIds image\n",
    "    Generate individually labeled RGB images\n",
    "    NOTE: The generated file has a random uuid string and the class label joined wiht __ (double underscores)\n",
    "    as the file name\n",
    "    '''\n",
    "    \n",
    "    root_path = '/ssd_scratch/cvit/dksingh/idd/expanded_images/'\n",
    "    orig_img_path = path_tuple[0]\n",
    "    label_img_path = path_tuple[1]\n",
    "    \n",
    "    orig_img = Image.open(orig_img_path)\n",
    "    label_img = Image.open(label_img_path)\n",
    "    \n",
    "    uniq_label_ids = set(np.unique(label_img))\n",
    "    blacklisted_label_ids = {2,5,18,27,28,34,35,36,37,38,39}\n",
    "    filtered_label_ids = uniq_label_ids - blacklisted_label_ids\n",
    "    \n",
    "    \n",
    "    \n",
    "    for label_id in filtered_label_ids:\n",
    "        chosen_label_mask = np.array(label_img) == label_id\n",
    "        chosen_label_mask_stack = np.stack((chosen_label_mask, chosen_label_mask, chosen_label_mask), axis=-1)\n",
    "        chosen_label_mask_img = np.array(orig_img) * chosen_label_mask_stack\n",
    "        \n",
    "        random_file_name = uuid.uuid1().hex+\"__\"+str(label_id)+\".png\"\n",
    "        \n",
    "        temp_img = Image.fromarray(chosen_label_mask_img)\n",
    "        temp_img.save(root_path+random_file_name)\n",
    "        \n",
    "#         print(f\"saved: {random_file_name}\")    "
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### To test a sample"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "# path_tuple= ('/ssd_scratch/cvit/dksingh/cityscapes/leftImg8bit/train/cologne/cologne_000149_000019_leftImg8bit.png','/ssd_scratch/cvit/dksingh/cityscapes/gtFine/train/cologne/cologne_000149_000019_gtFine_labelIds.png')\n",
    "# delabeler(path_tuple)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Generate the path list"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "def get_label_image_path(img_path):\n",
    "    return img_path.replace(\"leftImg8bit\",\"gtFine\",1)[0:-15]+\"gtFine_labelids.png\"\n",
    "\n",
    "file_pointer = open(\"./train_imgs_idd_file_list.txt\", 'r')\n",
    "img_path_list = [line.rstrip() for line in file_pointer.readlines()]\n",
    "list_of_path_tuples = [(img_path, get_label_image_path(img_path)) for img_path in img_path_list]"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Start the multiprocessing"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "saved: 107f482cbba911eaba48ac1f6b21d262__0.pngsaved: 105e5072bba911eab6aaac1f6b21d262__0.png\n",
      "\n",
      "saved: 10844e4ebba911eaa8e9ac1f6b21d262__0.png\n",
      "saved: 107d978ebba911eaa7fbac1f6b21d262__0.png\n",
      "saved: 107fde86bba911eaad1cac1f6b21d262__0.pngsaved: 107ea62ebba911eaa5eaac1f6b21d262__0.pngsaved: 107a403ebba911eaaab4ac1f6b21d262__0.png\n",
      "\n",
      "\n",
      "saved: 10807b70bba911eaa393ac1f6b21d262__0.png\n",
      "saved: 126dceb0bba911eaa8e9ac1f6b21d262__33.png\n",
      "saved: 129bc108bba911eaad1cac1f6b21d262__33.png\n",
      "saved: 1207e3acbba911eab6aaac1f6b21d262__33.pngsaved: 108280bebba911eaaba9ac1f6b21d262__0.png\n",
      "saved: 12056456bba911eaba48ac1f6b21d262__33.png\n",
      "\n",
      "saved: 1278f970bba911eaa7fbac1f6b21d262__33.png\n",
      "saved: 12a501bebba911eaa5eaac1f6b21d262__32.png\n",
      "saved: 10a8f898bba911eaaef0ac1f6b21d262__0.pngsaved: 12aae926bba911eaaab4ac1f6b21d262__33.png\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Process ForkPoolWorker-21:\n",
      "Process ForkPoolWorker-27:\n",
      "Process ForkPoolWorker-19:\n",
      "Process ForkPoolWorker-8:\n",
      "Process ForkPoolWorker-11:\n",
      "Process ForkPoolWorker-15:\n",
      "Process ForkPoolWorker-5:\n",
      "Process ForkPoolWorker-33:\n",
      "Traceback (most recent call last):\n",
      "Process ForkPoolWorker-4:\n",
      "Process ForkPoolWorker-24:\n",
      "Process ForkPoolWorker-25:\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "Process ForkPoolWorker-2:\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 297, in _bootstrap\n",
      "    self.run()\n",
      "Traceback (most recent call last):\n",
      "Process ForkPoolWorker-3:\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "Process ForkPoolWorker-18:\n",
      "Process ForkPoolWorker-30:\n",
      "Traceback (most recent call last):\n",
      "Process ForkPoolWorker-32:\n",
      "Traceback (most recent call last):\n",
      "Process ForkPoolWorker-31:\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 496, in _save\n",
      "    fh = fp.fileno()\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 496, in _save\n",
      "    fh = fp.fileno()\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 496, in _save\n",
      "    fh = fp.fileno()\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 496, in _save\n",
      "    fh = fp.fileno()\n",
      "Process ForkPoolWorker-36:\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 496, in _save\n",
      "    fh = fp.fileno()\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 99, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 496, in _save\n",
      "    fh = fp.fileno()\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 496, in _save\n",
      "    fh = fp.fileno()\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 496, in _save\n",
      "    fh = fp.fileno()\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "Process ForkPoolWorker-34:\n",
      "Process ForkPoolWorker-14:\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 496, in _save\n",
      "    fh = fp.fileno()\n",
      "Process ForkPoolWorker-1:\n",
      "Process ForkPoolWorker-7:\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 496, in _save\n",
      "    fh = fp.fileno()\n",
      "AttributeError: '_idat' object has no attribute 'fileno'\n",
      "AttributeError: '_idat' object has no attribute 'fileno'\n",
      "AttributeError: '_idat' object has no attribute 'fileno'\n",
      "AttributeError: '_idat' object has no attribute 'fileno'\n",
      "Process ForkPoolWorker-10:\n",
      "AttributeError: '_idat' object has no attribute 'fileno'\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 121, in worker\n",
      "    result = (True, func(*args, **kwds))\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "AttributeError: '_idat' object has no attribute 'fileno'\n",
      "Traceback (most recent call last):\n",
      "AttributeError: '_idat' object has no attribute 'fileno'\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 496, in _save\n",
      "    fh = fp.fileno()\n",
      "AttributeError: '_idat' object has no attribute 'fileno'\n",
      "Process ForkPoolWorker-22:\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 496, in _save\n",
      "    fh = fp.fileno()\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 496, in _save\n",
      "    fh = fp.fileno()\n",
      "Traceback (most recent call last):\n",
      "AttributeError: '_idat' object has no attribute 'fileno'\n",
      "AttributeError: '_idat' object has no attribute 'fileno'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Process ForkPoolWorker-35:\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Process ForkPoolWorker-38:\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 44, in mapstar\n",
      "    return list(map(*args))\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 496, in _save\n",
      "    fh = fp.fileno()\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 496, in _save\n",
      "    fh = fp.fileno()\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 496, in _save\n",
      "    fh = fp.fileno()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 496, in _save\n",
      "    fh = fp.fileno()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "AttributeError: '_idat' object has no attribute 'fileno'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "AttributeError: '_idat' object has no attribute 'fileno'\n",
      "AttributeError: '_idat' object has no attribute 'fileno'\n",
      "Process ForkPoolWorker-26:\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 496, in _save\n",
      "    fh = fp.fileno()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 496, in _save\n",
      "    fh = fp.fileno()\n",
      "  File \"<ipython-input-2-e428310e530e>\", line 32, in delabeler\n",
      "    print(f\"saved: {random_file_name}\")\n",
      "AttributeError: '_idat' object has no attribute 'fileno'\n",
      "AttributeError: '_idat' object has no attribute 'fileno'\n",
      "AttributeError: '_idat' object has no attribute 'fileno'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 496, in _save\n",
      "    fh = fp.fileno()\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 496, in _save\n",
      "    fh = fp.fileno()\n",
      "Process ForkPoolWorker-40:\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 496, in _save\n",
      "    fh = fp.fileno()\n",
      "AttributeError: '_idat' object has no attribute 'fileno'\n",
      "Traceback (most recent call last):\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Process ForkPoolWorker-39:\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "AttributeError: '_idat' object has no attribute 'fileno'\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 297, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 297, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 297, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 297, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 496, in _save\n",
      "    fh = fp.fileno()\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 496, in _save\n",
      "    fh = fp.fileno()\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Process ForkPoolWorker-17:\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 297, in _bootstrap\n",
      "    self.run()\n",
      "AttributeError: '_idat' object has no attribute 'fileno'\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/ipykernel/iostream.py\", line 412, in write\n",
      "    self.pub_thread.schedule(self._flush)\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 297, in _bootstrap\n",
      "    self.run()\n",
      "AttributeError: '_idat' object has no attribute 'fileno'\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 496, in _save\n",
      "    fh = fp.fileno()\n",
      "AttributeError: '_idat' object has no attribute 'fileno'\n",
      "Process ForkPoolWorker-20:\n",
      "Traceback (most recent call last):\n",
      "AttributeError: '_idat' object has no attribute 'fileno'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 297, in _bootstrap\n",
      "    self.run()\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 297, in _bootstrap\n",
      "    self.run()\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "Process ForkPoolWorker-12:\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 121, in worker\n",
      "    result = (True, func(*args, **kwds))\n",
      "Process ForkPoolWorker-37:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 496, in _save\n",
      "    fh = fp.fileno()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 297, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 297, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 99, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 99, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 99, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 99, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "AttributeError: '_idat' object has no attribute 'fileno'\n",
      "AttributeError: '_idat' object has no attribute 'fileno'\n",
      "Process ForkPoolWorker-6:\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 99, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/ipykernel/iostream.py\", line 207, in schedule\n",
      "    f()\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 99, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "AttributeError: '_idat' object has no attribute 'fileno'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Process ForkPoolWorker-16:\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 496, in _save\n",
      "    fh = fp.fileno()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 99, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 297, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 99, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 297, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 297, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 496, in _save\n",
      "    fh = fp.fileno()\n",
      "AttributeError: '_idat' object has no attribute 'fileno'\n",
      "Process ForkPoolWorker-29:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 99, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 99, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "Process ForkPoolWorker-13:\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 121, in worker\n",
      "    result = (True, func(*args, **kwds))\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 121, in worker\n",
      "    result = (True, func(*args, **kwds))\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 121, in worker\n",
      "    result = (True, func(*args, **kwds))\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 121, in worker\n",
      "    result = (True, func(*args, **kwds))\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 121, in worker\n",
      "    result = (True, func(*args, **kwds))\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/ipykernel/iostream.py\", line 384, in _flush\n",
      "    parent=self.parent_header, ident=self.topic)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 297, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 297, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 297, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 121, in worker\n",
      "    result = (True, func(*args, **kwds))\n",
      "Traceback (most recent call last):\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "AttributeError: '_idat' object has no attribute 'fileno'\n",
      "Process ForkPoolWorker-23:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 297, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 121, in worker\n",
      "    result = (True, func(*args, **kwds))\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 99, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 121, in worker\n",
      "    result = (True, func(*args, **kwds))\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 99, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 99, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "AttributeError: '_idat' object has no attribute 'fileno'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Process ForkPoolWorker-9:\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 297, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 121, in worker\n",
      "    result = (True, func(*args, **kwds))\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 44, in mapstar\n",
      "    return list(map(*args))\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 44, in mapstar\n",
      "    return list(map(*args))\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 44, in mapstar\n",
      "    return list(map(*args))\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 44, in mapstar\n",
      "    return list(map(*args))\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 496, in _save\n",
      "    fh = fp.fileno()\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 496, in _save\n",
      "    fh = fp.fileno()\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 496, in _save\n",
      "    fh = fp.fileno()\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 297, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 44, in mapstar\n",
      "    return list(map(*args))\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 496, in _save\n",
      "    fh = fp.fileno()\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 496, in _save\n",
      "    fh = fp.fileno()\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/jupyter_client/session.py\", line 757, in send\n",
      "    stream.send_multipart(to_send, copy=copy)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 99, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 99, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 99, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 44, in mapstar\n",
      "    return list(map(*args))\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 297, in _bootstrap\n",
      "    self.run()\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 297, in _bootstrap\n",
      "    self.run()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 297, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 99, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 44, in mapstar\n",
      "    return list(map(*args))\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 121, in worker\n",
      "    result = (True, func(*args, **kwds))\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 496, in _save\n",
      "    fh = fp.fileno()\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 44, in mapstar\n",
      "    return list(map(*args))\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 121, in worker\n",
      "    result = (True, func(*args, **kwds))\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 121, in worker\n",
      "    result = (True, func(*args, **kwds))\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 99, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 496, in _save\n",
      "    fh = fp.fileno()\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 44, in mapstar\n",
      "    return list(map(*args))\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 44, in mapstar\n",
      "    return list(map(*args))\n",
      "  File \"<ipython-input-2-e428310e530e>\", line 30, in delabeler\n",
      "    temp_img.save(root_path+random_file_name)\n",
      "  File \"<ipython-input-2-e428310e530e>\", line 30, in delabeler\n",
      "    temp_img.save(root_path+random_file_name)\n",
      "  File \"<ipython-input-2-e428310e530e>\", line 30, in delabeler\n",
      "    temp_img.save(root_path+random_file_name)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 496, in _save\n",
      "    fh = fp.fileno()\n",
      "  File \"<ipython-input-2-e428310e530e>\", line 30, in delabeler\n",
      "    temp_img.save(root_path+random_file_name)\n",
      "AttributeError: '_idat' object has no attribute 'fileno'\n",
      "AttributeError: '_idat' object has no attribute 'fileno'\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 297, in _bootstrap\n",
      "    self.run()\n",
      "AttributeError: '_idat' object has no attribute 'fileno'\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 297, in _bootstrap\n",
      "    self.run()\n",
      "  File \"<ipython-input-2-e428310e530e>\", line 30, in delabeler\n",
      "    temp_img.save(root_path+random_file_name)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 99, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "AttributeError: '_idat' object has no attribute 'fileno'\n",
      "AttributeError: '_idat' object has no attribute 'fileno'\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/ipykernel/iostream.py\", line 214, in send_multipart\n",
      "    self.schedule(lambda : self._really_send(*args, **kwargs))\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 121, in worker\n",
      "    result = (True, func(*args, **kwds))\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 121, in worker\n",
      "    result = (True, func(*args, **kwds))\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 121, in worker\n",
      "    result = (True, func(*args, **kwds))\n",
      "  File \"<ipython-input-2-e428310e530e>\", line 30, in delabeler\n",
      "    temp_img.save(root_path+random_file_name)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 99, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 297, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 99, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 99, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 121, in worker\n",
      "    result = (True, func(*args, **kwds))\n",
      "  File \"<ipython-input-2-e428310e530e>\", line 30, in delabeler\n",
      "    temp_img.save(root_path+random_file_name)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 44, in mapstar\n",
      "    return list(map(*args))\n",
      "AttributeError: '_idat' object has no attribute 'fileno'\n",
      "  File \"<ipython-input-2-e428310e530e>\", line 30, in delabeler\n",
      "    temp_img.save(root_path+random_file_name)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 510, in _save\n",
      "    l, s, d = e.encode(bufsize)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 44, in mapstar\n",
      "    return list(map(*args))\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 44, in mapstar\n",
      "    return list(map(*args))\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 297, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 121, in worker\n",
      "    result = (True, func(*args, **kwds))\n",
      "AttributeError: '_idat' object has no attribute 'fileno'\n",
      "  File \"<ipython-input-2-e428310e530e>\", line 30, in delabeler\n",
      "    temp_img.save(root_path+random_file_name)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 496, in _save\n",
      "    fh = fp.fileno()\n",
      "  File \"<ipython-input-2-e428310e530e>\", line 30, in delabeler\n",
      "    temp_img.save(root_path+random_file_name)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/Image.py\", line 2134, in save\n",
      "    save_handler(self, fp, filename)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/Image.py\", line 2134, in save\n",
      "    save_handler(self, fp, filename)\n",
      "AttributeError: '_idat' object has no attribute 'fileno'\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/Image.py\", line 2134, in save\n",
      "    save_handler(self, fp, filename)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/Image.py\", line 2134, in save\n",
      "    save_handler(self, fp, filename)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 99, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 99, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 121, in worker\n",
      "    result = (True, func(*args, **kwds))\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/Image.py\", line 2134, in save\n",
      "    save_handler(self, fp, filename)\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/ipykernel/iostream.py\", line 207, in schedule\n",
      "    f()\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 44, in mapstar\n",
      "    return list(map(*args))\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 44, in mapstar\n",
      "    return list(map(*args))\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 496, in _save\n",
      "    fh = fp.fileno()\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 44, in mapstar\n",
      "    return list(map(*args))\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/Image.py\", line 2134, in save\n",
      "    save_handler(self, fp, filename)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 121, in worker\n",
      "    result = (True, func(*args, **kwds))\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 121, in worker\n",
      "    result = (True, func(*args, **kwds))\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 99, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 297, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 121, in worker\n",
      "    result = (True, func(*args, **kwds))\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 44, in mapstar\n",
      "    return list(map(*args))\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/Image.py\", line 2134, in save\n",
      "    save_handler(self, fp, filename)\n",
      "  File \"<ipython-input-2-e428310e530e>\", line 30, in delabeler\n",
      "    temp_img.save(root_path+random_file_name)\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/Image.py\", line 2134, in save\n",
      "    save_handler(self, fp, filename)\n",
      "  File \"<ipython-input-2-e428310e530e>\", line 30, in delabeler\n",
      "    temp_img.save(root_path+random_file_name)\n",
      "  File \"<ipython-input-2-e428310e530e>\", line 30, in delabeler\n",
      "    temp_img.save(root_path+random_file_name)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 297, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 99, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 44, in mapstar\n",
      "    return list(map(*args))\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/Image.py\", line 2134, in save\n",
      "    save_handler(self, fp, filename)\n",
      "AttributeError: '_idat' object has no attribute 'fileno'\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/Image.py\", line 2134, in save\n",
      "    save_handler(self, fp, filename)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/PngImagePlugin.py\", line 1291, in _save\n",
      "    ImageFile._save(im, _idat(fp, chunk), [(\"zip\", (0, 0) + im.size, 0, rawmode)])\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/PngImagePlugin.py\", line 1291, in _save\n",
      "    ImageFile._save(im, _idat(fp, chunk), [(\"zip\", (0, 0) + im.size, 0, rawmode)])\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/PngImagePlugin.py\", line 1291, in _save\n",
      "    ImageFile._save(im, _idat(fp, chunk), [(\"zip\", (0, 0) + im.size, 0, rawmode)])\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/PngImagePlugin.py\", line 1291, in _save\n",
      "    ImageFile._save(im, _idat(fp, chunk), [(\"zip\", (0, 0) + im.size, 0, rawmode)])\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 121, in worker\n",
      "    result = (True, func(*args, **kwds))\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 121, in worker\n",
      "    result = (True, func(*args, **kwds))\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/PngImagePlugin.py\", line 1291, in _save\n",
      "    ImageFile._save(im, _idat(fp, chunk), [(\"zip\", (0, 0) + im.size, 0, rawmode)])\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 44, in mapstar\n",
      "    return list(map(*args))\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/ipykernel/iostream.py\", line 214, in <lambda>\n",
      "    self.schedule(lambda : self._really_send(*args, **kwargs))\n",
      "  File \"<ipython-input-2-e428310e530e>\", line 30, in delabeler\n",
      "    temp_img.save(root_path+random_file_name)\n",
      "  File \"<ipython-input-2-e428310e530e>\", line 30, in delabeler\n",
      "    temp_img.save(root_path+random_file_name)\n",
      "AttributeError: '_idat' object has no attribute 'fileno'\n",
      "  File \"<ipython-input-2-e428310e530e>\", line 30, in delabeler\n",
      "    temp_img.save(root_path+random_file_name)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/PngImagePlugin.py\", line 1291, in _save\n",
      "    ImageFile._save(im, _idat(fp, chunk), [(\"zip\", (0, 0) + im.size, 0, rawmode)])\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 44, in mapstar\n",
      "    return list(map(*args))\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 44, in mapstar\n",
      "    return list(map(*args))\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 121, in worker\n",
      "    result = (True, func(*args, **kwds))\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 99, in run\n",
      "    self._target(*self._args, **self._kwargs)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 44, in mapstar\n",
      "    return list(map(*args))\n",
      "  File \"<ipython-input-2-e428310e530e>\", line 30, in delabeler\n",
      "    temp_img.save(root_path+random_file_name)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/PngImagePlugin.py\", line 1291, in _save\n",
      "    ImageFile._save(im, _idat(fp, chunk), [(\"zip\", (0, 0) + im.size, 0, rawmode)])\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/Image.py\", line 2134, in save\n",
      "    save_handler(self, fp, filename)\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/PngImagePlugin.py\", line 1291, in _save\n",
      "    ImageFile._save(im, _idat(fp, chunk), [(\"zip\", (0, 0) + im.size, 0, rawmode)])\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/Image.py\", line 2134, in save\n",
      "    save_handler(self, fp, filename)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/Image.py\", line 2134, in save\n",
      "    save_handler(self, fp, filename)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 99, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 121, in worker\n",
      "    result = (True, func(*args, **kwds))\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-2-e428310e530e>\", line 30, in delabeler\n",
      "    temp_img.save(root_path+random_file_name)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/PngImagePlugin.py\", line 1291, in _save\n",
      "    ImageFile._save(im, _idat(fp, chunk), [(\"zip\", (0, 0) + im.size, 0, rawmode)])\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/PngImagePlugin.py\", line 1291, in _save\n",
      "    ImageFile._save(im, _idat(fp, chunk), [(\"zip\", (0, 0) + im.size, 0, rawmode)])\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 510, in _save\n",
      "    l, s, d = e.encode(bufsize)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 510, in _save\n",
      "    l, s, d = e.encode(bufsize)\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 510, in _save\n",
      "    l, s, d = e.encode(bufsize)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 297, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 297, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 44, in mapstar\n",
      "    return list(map(*args))\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 297, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 44, in mapstar\n",
      "    return list(map(*args))\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 510, in _save\n",
      "    l, s, d = e.encode(bufsize)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 297, in _bootstrap\n",
      "    self.run()\n",
      "  File \"<ipython-input-2-e428310e530e>\", line 30, in delabeler\n",
      "    temp_img.save(root_path+random_file_name)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 297, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/ipykernel/iostream.py\", line 230, in _really_send\n",
      "    ctx.term()\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/Image.py\", line 2134, in save\n",
      "    save_handler(self, fp, filename)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/Image.py\", line 2134, in save\n",
      "    save_handler(self, fp, filename)\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/Image.py\", line 2134, in save\n",
      "    save_handler(self, fp, filename)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 510, in _save\n",
      "    l, s, d = e.encode(bufsize)\n",
      "  File \"<ipython-input-2-e428310e530e>\", line 30, in delabeler\n",
      "    temp_img.save(root_path+random_file_name)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 44, in mapstar\n",
      "    return list(map(*args))\n",
      "  File \"<ipython-input-2-e428310e530e>\", line 30, in delabeler\n",
      "    temp_img.save(root_path+random_file_name)\n",
      "  File \"<ipython-input-2-e428310e530e>\", line 30, in delabeler\n",
      "    temp_img.save(root_path+random_file_name)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/Image.py\", line 2134, in save\n",
      "    save_handler(self, fp, filename)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 121, in worker\n",
      "    result = (True, func(*args, **kwds))\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/PngImagePlugin.py\", line 1291, in _save\n",
      "    ImageFile._save(im, _idat(fp, chunk), [(\"zip\", (0, 0) + im.size, 0, rawmode)])\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 510, in _save\n",
      "    l, s, d = e.encode(bufsize)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 297, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 510, in _save\n",
      "    l, s, d = e.encode(bufsize)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/PngImagePlugin.py\", line 1291, in _save\n",
      "    ImageFile._save(im, _idat(fp, chunk), [(\"zip\", (0, 0) + im.size, 0, rawmode)])\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/PngImagePlugin.py\", line 1291, in _save\n",
      "    ImageFile._save(im, _idat(fp, chunk), [(\"zip\", (0, 0) + im.size, 0, rawmode)])\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 121, in worker\n",
      "    result = (True, func(*args, **kwds))\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 44, in mapstar\n",
      "    return list(map(*args))\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/Image.py\", line 2134, in save\n",
      "    save_handler(self, fp, filename)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 297, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 510, in _save\n",
      "    l, s, d = e.encode(bufsize)\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 510, in _save\n",
      "    l, s, d = e.encode(bufsize)\n",
      "KeyboardInterrupt\n",
      "KeyboardInterrupt\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 297, in _bootstrap\n",
      "    self.run()\n",
      "KeyboardInterrupt\n",
      "KeyboardInterrupt\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 99, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 99, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-2-e428310e530e>\", line 30, in delabeler\n",
      "    temp_img.save(root_path+random_file_name)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 99, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-2-e428310e530e>\", line 30, in delabeler\n",
      "    temp_img.save(root_path+random_file_name)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/Image.py\", line 2134, in save\n",
      "    save_handler(self, fp, filename)\n",
      "KeyboardInterrupt\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 99, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 99, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/PngImagePlugin.py\", line 1291, in _save\n",
      "    ImageFile._save(im, _idat(fp, chunk), [(\"zip\", (0, 0) + im.size, 0, rawmode)])\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/PngImagePlugin.py\", line 1291, in _save\n",
      "    ImageFile._save(im, _idat(fp, chunk), [(\"zip\", (0, 0) + im.size, 0, rawmode)])\n",
      "  File \"zmq/backend/cython/context.pyx\", line 91, in zmq.backend.cython.context.Context.term\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/PngImagePlugin.py\", line 1291, in _save\n",
      "    ImageFile._save(im, _idat(fp, chunk), [(\"zip\", (0, 0) + im.size, 0, rawmode)])\n",
      "KeyboardInterrupt\n",
      "  File \"<ipython-input-2-e428310e530e>\", line 30, in delabeler\n",
      "    temp_img.save(root_path+random_file_name)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/Image.py\", line 2134, in save\n",
      "    save_handler(self, fp, filename)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/Image.py\", line 2134, in save\n",
      "    save_handler(self, fp, filename)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 44, in mapstar\n",
      "    return list(map(*args))\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/PngImagePlugin.py\", line 1291, in _save\n",
      "    ImageFile._save(im, _idat(fp, chunk), [(\"zip\", (0, 0) + im.size, 0, rawmode)])\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/Image.py\", line 2134, in save\n",
      "    save_handler(self, fp, filename)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 510, in _save\n",
      "    l, s, d = e.encode(bufsize)\n",
      "KeyboardInterrupt\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 99, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "KeyboardInterrupt\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 510, in _save\n",
      "    l, s, d = e.encode(bufsize)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 510, in _save\n",
      "    l, s, d = e.encode(bufsize)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 44, in mapstar\n",
      "    return list(map(*args))\n",
      "  File \"<ipython-input-2-e428310e530e>\", line 30, in delabeler\n",
      "    temp_img.save(root_path+random_file_name)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 99, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/PngImagePlugin.py\", line 1291, in _save\n",
      "    ImageFile._save(im, _idat(fp, chunk), [(\"zip\", (0, 0) + im.size, 0, rawmode)])\n",
      "KeyboardInterrupt\n",
      "KeyboardInterrupt\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 297, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 99, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 121, in worker\n",
      "    result = (True, func(*args, **kwds))\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 121, in worker\n",
      "    result = (True, func(*args, **kwds))\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/Image.py\", line 2134, in save\n",
      "    save_handler(self, fp, filename)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 121, in worker\n",
      "    result = (True, func(*args, **kwds))\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/Image.py\", line 2134, in save\n",
      "    save_handler(self, fp, filename)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 121, in worker\n",
      "    result = (True, func(*args, **kwds))\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/PngImagePlugin.py\", line 1291, in _save\n",
      "    ImageFile._save(im, _idat(fp, chunk), [(\"zip\", (0, 0) + im.size, 0, rawmode)])\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 121, in worker\n",
      "    result = (True, func(*args, **kwds))\n",
      "  File \"zmq/backend/cython/checkrc.pxd\", line 13, in zmq.backend.cython.checkrc._check_rc\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 510, in _save\n",
      "    l, s, d = e.encode(bufsize)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 510, in _save\n",
      "    l, s, d = e.encode(bufsize)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 297, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 510, in _save\n",
      "    l, s, d = e.encode(bufsize)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/PngImagePlugin.py\", line 1291, in _save\n",
      "    ImageFile._save(im, _idat(fp, chunk), [(\"zip\", (0, 0) + im.size, 0, rawmode)])\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/PngImagePlugin.py\", line 1291, in _save\n",
      "    ImageFile._save(im, _idat(fp, chunk), [(\"zip\", (0, 0) + im.size, 0, rawmode)])\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/Image.py\", line 2134, in save\n",
      "    save_handler(self, fp, filename)\n",
      "  File \"<ipython-input-2-e428310e530e>\", line 30, in delabeler\n",
      "    temp_img.save(root_path+random_file_name)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 510, in _save\n",
      "    l, s, d = e.encode(bufsize)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/PngImagePlugin.py\", line 1291, in _save\n",
      "    ImageFile._save(im, _idat(fp, chunk), [(\"zip\", (0, 0) + im.size, 0, rawmode)])\n",
      "KeyboardInterrupt\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 121, in worker\n",
      "    result = (True, func(*args, **kwds))\n",
      "KeyboardInterrupt\n",
      "KeyboardInterrupt\n",
      "  File \"<ipython-input-2-e428310e530e>\", line 30, in delabeler\n",
      "    temp_img.save(root_path+random_file_name)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/Image.py\", line 2134, in save\n",
      "    save_handler(self, fp, filename)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 121, in worker\n",
      "    result = (True, func(*args, **kwds))\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 510, in _save\n",
      "    l, s, d = e.encode(bufsize)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 99, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 121, in worker\n",
      "    result = (True, func(*args, **kwds))\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 44, in mapstar\n",
      "    return list(map(*args))\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/PngImagePlugin.py\", line 1291, in _save\n",
      "    ImageFile._save(im, _idat(fp, chunk), [(\"zip\", (0, 0) + im.size, 0, rawmode)])\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 44, in mapstar\n",
      "    return list(map(*args))\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 44, in mapstar\n",
      "    return list(map(*args))\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/PngImagePlugin.py\", line 1291, in _save\n",
      "    ImageFile._save(im, _idat(fp, chunk), [(\"zip\", (0, 0) + im.size, 0, rawmode)])\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 44, in mapstar\n",
      "    return list(map(*args))\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 510, in _save\n",
      "    l, s, d = e.encode(bufsize)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 44, in mapstar\n",
      "    return list(map(*args))\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/process.py\", line 99, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "KeyboardInterrupt\n",
      "KeyboardInterrupt\n",
      "KeyboardInterrupt\n",
      "KeyboardInterrupt\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/PngImagePlugin.py\", line 1291, in _save\n",
      "    ImageFile._save(im, _idat(fp, chunk), [(\"zip\", (0, 0) + im.size, 0, rawmode)])\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 510, in _save\n",
      "    l, s, d = e.encode(bufsize)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 510, in _save\n",
      "    l, s, d = e.encode(bufsize)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/Image.py\", line 2134, in save\n",
      "    save_handler(self, fp, filename)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 510, in _save\n",
      "    l, s, d = e.encode(bufsize)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 510, in _save\n",
      "    l, s, d = e.encode(bufsize)\n",
      "KeyboardInterrupt\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 44, in mapstar\n",
      "    return list(map(*args))\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/Image.py\", line 2134, in save\n",
      "    save_handler(self, fp, filename)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/PngImagePlugin.py\", line 1291, in _save\n",
      "    ImageFile._save(im, _idat(fp, chunk), [(\"zip\", (0, 0) + im.size, 0, rawmode)])\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 44, in mapstar\n",
      "    return list(map(*args))\n",
      "KeyboardInterrupt\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 121, in worker\n",
      "    result = (True, func(*args, **kwds))\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 44, in mapstar\n",
      "    return list(map(*args))\n",
      "  File \"<ipython-input-2-e428310e530e>\", line 30, in delabeler\n",
      "    temp_img.save(root_path+random_file_name)\n",
      "  File \"<ipython-input-2-e428310e530e>\", line 30, in delabeler\n",
      "    temp_img.save(root_path+random_file_name)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 510, in _save\n",
      "    l, s, d = e.encode(bufsize)\n",
      "  File \"<ipython-input-2-e428310e530e>\", line 30, in delabeler\n",
      "    temp_img.save(root_path+random_file_name)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 510, in _save\n",
      "    l, s, d = e.encode(bufsize)\n",
      "  File \"<ipython-input-2-e428310e530e>\", line 30, in delabeler\n",
      "    temp_img.save(root_path+random_file_name)\n",
      "KeyboardInterrupt\n",
      "  File \"<ipython-input-2-e428310e530e>\", line 30, in delabeler\n",
      "    temp_img.save(root_path+random_file_name)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 121, in worker\n",
      "    result = (True, func(*args, **kwds))\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 510, in _save\n",
      "    l, s, d = e.encode(bufsize)\n",
      "KeyboardInterrupt\n",
      "KeyboardInterrupt\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/PngImagePlugin.py\", line 1291, in _save\n",
      "    ImageFile._save(im, _idat(fp, chunk), [(\"zip\", (0, 0) + im.size, 0, rawmode)])\n",
      "KeyboardInterrupt\n",
      "  File \"<ipython-input-2-e428310e530e>\", line 30, in delabeler\n",
      "    temp_img.save(root_path+random_file_name)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/PngImagePlugin.py\", line 1291, in _save\n",
      "    ImageFile._save(im, _idat(fp, chunk), [(\"zip\", (0, 0) + im.size, 0, rawmode)])\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 510, in _save\n",
      "    l, s, d = e.encode(bufsize)\n",
      "  File \"<ipython-input-2-e428310e530e>\", line 30, in delabeler\n",
      "    temp_img.save(root_path+random_file_name)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 44, in mapstar\n",
      "    return list(map(*args))\n",
      "  File \"<ipython-input-2-e428310e530e>\", line 30, in delabeler\n",
      "    temp_img.save(root_path+random_file_name)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/Image.py\", line 2134, in save\n",
      "    save_handler(self, fp, filename)\n",
      "KeyboardInterrupt\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/Image.py\", line 2134, in save\n",
      "    save_handler(self, fp, filename)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/Image.py\", line 2134, in save\n",
      "    save_handler(self, fp, filename)\n",
      "KeyboardInterrupt\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/Image.py\", line 2134, in save\n",
      "    save_handler(self, fp, filename)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/Image.py\", line 2134, in save\n",
      "    save_handler(self, fp, filename)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\", line 44, in mapstar\n",
      "    return list(map(*args))\n",
      "KeyboardInterrupt\n"
     ]
    },
    {
     "ename": "KeyboardInterrupt",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mKeyboardInterrupt\u001b[0m                         Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-5-2e6fdb402544>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0mstart_time\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mtime\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mtime\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      2\u001b[0m \u001b[0mpool\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mmultiprocessing\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mPool\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mprocesses\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mmultiprocessing\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mcpu_count\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 3\u001b[0;31m \u001b[0mpool\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mmap\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mdelabeler\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0mlist_of_path_tuples\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      4\u001b[0m \u001b[0mpool\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mclose\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34mf'Total generation time: {time.time()-start_time} seconds'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\u001b[0m in \u001b[0;36mmap\u001b[0;34m(self, func, iterable, chunksize)\u001b[0m\n\u001b[1;32m    266\u001b[0m         \u001b[0;32min\u001b[0m \u001b[0ma\u001b[0m \u001b[0mlist\u001b[0m \u001b[0mthat\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0mreturned\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    267\u001b[0m         '''\n\u001b[0;32m--> 268\u001b[0;31m         \u001b[0;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_map_async\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mfunc\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0miterable\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mmapstar\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mchunksize\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mget\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    269\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    270\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0mstarmap\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mfunc\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0miterable\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mchunksize\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;32mNone\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\u001b[0m in \u001b[0;36mget\u001b[0;34m(self, timeout)\u001b[0m\n\u001b[1;32m    649\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    650\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0mget\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mtimeout\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;32mNone\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 651\u001b[0;31m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mwait\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mtimeout\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    652\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mready\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    653\u001b[0m             \u001b[0;32mraise\u001b[0m \u001b[0mTimeoutError\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/dev/lib/python3.7/multiprocessing/pool.py\u001b[0m in \u001b[0;36mwait\u001b[0;34m(self, timeout)\u001b[0m\n\u001b[1;32m    646\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    647\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0mwait\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mtimeout\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;32mNone\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 648\u001b[0;31m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_event\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mwait\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mtimeout\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    649\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    650\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0mget\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mtimeout\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;32mNone\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/dev/lib/python3.7/threading.py\u001b[0m in \u001b[0;36mwait\u001b[0;34m(self, timeout)\u001b[0m\n\u001b[1;32m    550\u001b[0m             \u001b[0msignaled\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_flag\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    551\u001b[0m             \u001b[0;32mif\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0msignaled\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 552\u001b[0;31m                 \u001b[0msignaled\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_cond\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mwait\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mtimeout\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    553\u001b[0m             \u001b[0;32mreturn\u001b[0m \u001b[0msignaled\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    554\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/dev/lib/python3.7/threading.py\u001b[0m in \u001b[0;36mwait\u001b[0;34m(self, timeout)\u001b[0m\n\u001b[1;32m    294\u001b[0m         \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m    \u001b[0;31m# restore state no matter what (e.g., KeyboardInterrupt)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    295\u001b[0m             \u001b[0;32mif\u001b[0m \u001b[0mtimeout\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 296\u001b[0;31m                 \u001b[0mwaiter\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0macquire\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    297\u001b[0m                 \u001b[0mgotit\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;32mTrue\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    298\u001b[0m             \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mKeyboardInterrupt\u001b[0m: "
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/Image.py\", line 2134, in save\n",
      "    save_handler(self, fp, filename)\n",
      "KeyboardInterrupt\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 510, in _save\n",
      "    l, s, d = e.encode(bufsize)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/Image.py\", line 2134, in save\n",
      "    save_handler(self, fp, filename)\n",
      "  File \"<ipython-input-2-e428310e530e>\", line 30, in delabeler\n",
      "    temp_img.save(root_path+random_file_name)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/Image.py\", line 2134, in save\n",
      "    save_handler(self, fp, filename)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/PngImagePlugin.py\", line 1291, in _save\n",
      "    ImageFile._save(im, _idat(fp, chunk), [(\"zip\", (0, 0) + im.size, 0, rawmode)])\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/PngImagePlugin.py\", line 1291, in _save\n",
      "    ImageFile._save(im, _idat(fp, chunk), [(\"zip\", (0, 0) + im.size, 0, rawmode)])\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/PngImagePlugin.py\", line 1291, in _save\n",
      "    ImageFile._save(im, _idat(fp, chunk), [(\"zip\", (0, 0) + im.size, 0, rawmode)])\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/PngImagePlugin.py\", line 1291, in _save\n",
      "    ImageFile._save(im, _idat(fp, chunk), [(\"zip\", (0, 0) + im.size, 0, rawmode)])\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/PngImagePlugin.py\", line 1291, in _save\n",
      "    ImageFile._save(im, _idat(fp, chunk), [(\"zip\", (0, 0) + im.size, 0, rawmode)])\n",
      "  File \"<ipython-input-2-e428310e530e>\", line 30, in delabeler\n",
      "    temp_img.save(root_path+random_file_name)\n",
      "KeyboardInterrupt\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/PngImagePlugin.py\", line 1291, in _save\n",
      "    ImageFile._save(im, _idat(fp, chunk), [(\"zip\", (0, 0) + im.size, 0, rawmode)])\n",
      "KeyboardInterrupt\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/PngImagePlugin.py\", line 1291, in _save\n",
      "    ImageFile._save(im, _idat(fp, chunk), [(\"zip\", (0, 0) + im.size, 0, rawmode)])\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/Image.py\", line 2134, in save\n",
      "    save_handler(self, fp, filename)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/PngImagePlugin.py\", line 1291, in _save\n",
      "    ImageFile._save(im, _idat(fp, chunk), [(\"zip\", (0, 0) + im.size, 0, rawmode)])\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 510, in _save\n",
      "    l, s, d = e.encode(bufsize)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 510, in _save\n",
      "    l, s, d = e.encode(bufsize)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 510, in _save\n",
      "    l, s, d = e.encode(bufsize)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 510, in _save\n",
      "    l, s, d = e.encode(bufsize)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 510, in _save\n",
      "    l, s, d = e.encode(bufsize)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/Image.py\", line 2134, in save\n",
      "    save_handler(self, fp, filename)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 510, in _save\n",
      "    l, s, d = e.encode(bufsize)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 510, in _save\n",
      "    l, s, d = e.encode(bufsize)\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/PngImagePlugin.py\", line 1291, in _save\n",
      "    ImageFile._save(im, _idat(fp, chunk), [(\"zip\", (0, 0) + im.size, 0, rawmode)])\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 510, in _save\n",
      "    l, s, d = e.encode(bufsize)\n",
      "KeyboardInterrupt\n",
      "KeyboardInterrupt\n",
      "KeyboardInterrupt\n",
      "KeyboardInterrupt\n",
      "KeyboardInterrupt\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/PngImagePlugin.py\", line 1291, in _save\n",
      "    ImageFile._save(im, _idat(fp, chunk), [(\"zip\", (0, 0) + im.size, 0, rawmode)])\n",
      "KeyboardInterrupt\n",
      "KeyboardInterrupt\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 510, in _save\n",
      "    l, s, d = e.encode(bufsize)\n",
      "KeyboardInterrupt\n",
      "  File \"/home/dksingh/anaconda3/envs/dev/lib/python3.7/site-packages/PIL/ImageFile.py\", line 510, in _save\n",
      "    l, s, d = e.encode(bufsize)\n",
      "KeyboardInterrupt\n",
      "KeyboardInterrupt\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "saved: 14ff34a2bba911eaaef0ac1f6b21d262__0.png\n",
      "saved: 15eb053abba911eabc6aac1f6b21d262__0.png\n",
      "saved: 162b7c6ebba911eaa159ac1f6b21d262__0.png\n",
      "saved: 15ebf5b2bba911ea93efac1f6b21d262__0.pngsaved: 166e99a4bba911eaa4ddac1f6b21d262__0.png\n",
      "\n",
      "saved: 1708baacbba911eaaef0ac1f6b21d262__32.png\n",
      "saved: 16996328bba911eaaa56ac1f6b21d262__0.png\n",
      "saved: 17df5b66bba911eabc6aac1f6b21d262__32.png\n",
      "saved: 1825fe18bba911eaa4ddac1f6b21d262__33.png\n",
      "saved: 182b91d4bba911ea93efac1f6b21d262__32.png\n",
      "saved: 1882ed1cbba911eaaef0ac1f6b21d262__33.png\n",
      "saved: 180022e2bba911eaa159ac1f6b21d262__32.pngsaved: 18e46f92bba911eaaa56ac1f6b21d262__33.png\n",
      "\n",
      "saved: 1a260bd6bba911eaaef0ac1f6b21d262__6.pngsaved: 17437534bba911ea96ceac1f6b21d262__0.png\n",
      "saved: 16aa3d74bba911eab96eac1f6b21d262__0.pngsaved: 1954fb90bba911eaa4ddac1f6b21d262__32.pngsaved: 192cc256bba911eabc6aac1f6b21d262__33.png\n",
      "\n",
      "\n",
      "saved: 16aad8babba911eaa524ac1f6b21d262__0.png\n",
      "\n",
      "saved: 16a996a8bba911eabad2ac1f6b21d262__0.png\n",
      "saved: 19a6bcd2bba911ea93efac1f6b21d262__33.pngsaved: 1abfdebebba911eaaef0ac1f6b21d262__8.png\n",
      "\n",
      "saved: 17440b8ebba911ea9ab1ac1f6b21d262__0.pngsaved: 1ad8ebf2bba911eaa4ddac1f6b21d262__8.png\n",
      "\n",
      "saved: 1ae793bebba911eabc6aac1f6b21d262__6.png\n",
      "saved: 1a97e9aebba911eaa159ac1f6b21d262__33.pngsaved: 1b3dac22bba911ea93efac1f6b21d262__6.png\n",
      "\n",
      "saved: 1b5451f2bba911eaaef0ac1f6b21d262__9.png\n",
      "saved: 1b78e38cbba911eaa4ddac1f6b21d262__11.png\n",
      "saved: 1b914256bba911eabc6aac1f6b21d262__8.pngsaved: 172009a0bba911eaa6afac1f6b21d262__0.png\n",
      "\n",
      "saved: 1bd2131cbba911eaa159ac1f6b21d262__3.pngsaved: 1bd45d70bba911ea93efac1f6b21d262__8.png\n",
      "\n",
      "saved: 1bf90922bba911eaaef0ac1f6b21d262__11.png\n",
      "saved: 1aa71e88bba911eaaa56ac1f6b21d262__32.png\n",
      "saved: 1c4679aabba911eabc6aac1f6b21d262__9.pngsaved: 17a51744bba911ea87cdac1f6b21d262__0.png\n",
      "saved: 1c7afe64bba911ea93efac1f6b21d262__9.png\n",
      "\n",
      "saved: 1c9b72c0bba911eaaef0ac1f6b21d262__12.png\n",
      "saved: 1791907abba911eab065ac1f6b21d262__0.pngsaved: 1cb5cd3cbba911eaaa56ac1f6b21d262__6.pngsaved: 1c700d38bba911eaa159ac1f6b21d262__6.png\n",
      "\n",
      "\n",
      "saved: 1cfd1d0ebba911eabc6aac1f6b21d262__11.png\n",
      "saved: 1c2144fabba911eaa4ddac1f6b21d262__12.pngsaved: 17922b0cbba911ea8cefac1f6b21d262__0.png\n",
      "saved: 1d207858bba911ea93efac1f6b21d262__11.png\n",
      "\n",
      "saved: 1d4c82ccbba911eaaef0ac1f6b21d262__13.png\n",
      "saved: 1d62eeeabba911eaaa56ac1f6b21d262__8.pngsaved: 17a47fa0bba911ea808bac1f6b21d262__0.png\n",
      "saved: 1d6ad88abba911eaa159ac1f6b21d262__8.png\n",
      "\n",
      "saved: 1dabc610bba911eaa4ddac1f6b21d262__13.pngsaved: 1d9156a4bba911eabc6aac1f6b21d262__12.png\n",
      "\n",
      "saved: 1dcf80fabba911ea93efac1f6b21d262__12.png\n",
      "saved: 1e117406bba911eaaa56ac1f6b21d262__9.pngsaved: 1e20cf5abba911eaa159ac1f6b21d262__9.png\n",
      "\n",
      "saved: 1e538d32bba911eabc6aac1f6b21d262__13.png\n",
      "saved: 1aea5d92bba911eab96eac1f6b21d262__33.pngsaved: 1e88a9ccbba911ea93efac1f6b21d262__13.png\n",
      "saved: 1d6ed2c8bba911ea87cdac1f6b21d262__32.png\n",
      "saved: 1b2b31dcbba911eaa524ac1f6b21d262__33.png\n",
      "\n",
      "saved: 1ee689a2bba911eaa159ac1f6b21d262__11.png\n",
      "saved: 1b2e7d38bba911ea96ceac1f6b21d262__33.pngsaved: 1e540b4abba911eaa4ddac1f6b21d262__14.png\n",
      "saved: 1ed09458bba911eaaa56ac1f6b21d262__11.png\n",
      "saved: 1bcbdef2bba911ea9ab1ac1f6b21d262__33.png\n",
      "\n",
      "saved: 1b4a9018bba911eabad2ac1f6b21d262__33.png\n",
      "saved: 1df74478bba911eaaef0ac1f6b21d262__14.png\n",
      "saved: 1e0b885cbba911ea8cefac1f6b21d262__33.png\n",
      "saved: 1e83ceb6bba911ea808bac1f6b21d262__33.pngsaved: 1fd7ab2abba911eaaa56ac1f6b21d262__12.pngsaved: 1fc606a4bba911eaa4ddac1f6b21d262__19.png\n",
      "\n",
      "\n",
      "saved: 200fd590bba911eaaef0ac1f6b21d262__19.png\n",
      "saved: 1f82c5d8bba911ea87cdac1f6b21d262__33.pngsaved: 1ef8c4dcbba911eabc6aac1f6b21d262__14.png\n",
      "\n",
      "saved: 1f32da64bba911ea93efac1f6b21d262__14.png\n",
      "saved: 1f8fb306bba911eaa159ac1f6b21d262__12.png\n",
      "saved: 20c5e722bba911eaa4ddac1f6b21d262__23.png\n",
      "saved: 1f1eb746bba911eab96eac1f6b21d262__32.png\n",
      "saved: 1f693cdabba911eaa524ac1f6b21d262__32.pngsaved: 20bf446cbba911eaaa56ac1f6b21d262__19.pngsaved: 20f40116bba911eaaef0ac1f6b21d262__20.png\n",
      "\n",
      "\n",
      "saved: 2110b716bba911eabc6aac1f6b21d262__19.pngsaved: 215e2d66bba911eaa159ac1f6b21d262__13.pngsaved: 2019aad4bba911eabad2ac1f6b21d262__32.png\n",
      "\n",
      "saved: 218c0b6ebba911eaa4ddac1f6b21d262__24.png\n",
      "\n",
      "saved: 214377c8bba911ea93efac1f6b21d262__19.png\n",
      "saved: 21d84d12bba911eaaef0ac1f6b21d262__21.pngsaved: 21a10d34bba911eab96eac1f6b21d262__3.png\n",
      "\n",
      "saved: 21d531febba911eaaa56ac1f6b21d262__20.pngsaved: 1dc68bbcbba911eab065ac1f6b21d262__33.pngsaved: 213efdb0bba911ea87cdac1f6b21d262__6.png\n",
      "saved: 21bd37b6bba911eaa524ac1f6b21d262__3.png\n",
      "\n",
      "saved: 21fa0038bba911eabc6aac1f6b21d262__20.pngsaved: 2206b0d0bba911eaa159ac1f6b21d262__14.png\n",
      "saved: 22238cc8bba911eaa4ddac1f6b21d262__25.png\n",
      "\n",
      "\n",
      "saved: 220d025abba911eabad2ac1f6b21d262__3.pngsaved: 2270de10bba911eaaef0ac1f6b21d262__23.png\n",
      "saved: 223671d0bba911ea93efac1f6b21d262__20.png\n",
      "\n",
      "saved: 2095c100bba911ea8cefac1f6b21d262__32.pngsaved: 227efee6bba911eab96eac1f6b21d262__8.png\n",
      "\n",
      "saved: 2292a93cbba911eaaa56ac1f6b21d262__23.pngsaved: 22b4bdbabba911eabc6aac1f6b21d262__21.png\n",
      "\n",
      "saved: 22c18e6ebba911eaa159ac1f6b21d262__19.pngsaved: 22ce6ed6bba911eaa4ddac1f6b21d262__26.pngsaved: 22a79900bba911eaa524ac1f6b21d262__8.png\n",
      "\n",
      "\n",
      "saved: 231a1232bba911ea93efac1f6b21d262__23.pngsaved: 230e0aaabba911eaaef0ac1f6b21d262__26.png\n",
      "saved: 2306eb26bba911eabad2ac1f6b21d262__8.png\n",
      "\n",
      "saved: 23604f9abba911eabc6aac1f6b21d262__23.pngsaved: 233ec636bba911eab96eac1f6b21d262__9.pngsaved: 22a9180cbba911ea87cdac1f6b21d262__8.png\n",
      "\n",
      "saved: 23731684bba911eaa159ac1f6b21d262__20.png\n",
      "saved: 235d3f44bba911eaaa56ac1f6b21d262__26.png\n",
      "\n",
      "saved: 2384f0b6bba911eaa524ac1f6b21d262__9.png\n",
      "saved: 20e98a24bba911ea808bac1f6b21d262__32.pngsaved: 23cf39f0bba911eaaef0ac1f6b21d262__29.pngsaved: 23cb25f4bba911ea93efac1f6b21d262__24.png\n",
      "\n",
      "\n",
      "saved: 2400508abba911eabc6aac1f6b21d262__24.pngsaved: 1c970118bba911eaa6afac1f6b21d262__33.pngsaved: 23dd8974bba911eabad2ac1f6b21d262__9.png\n",
      "saved: 235a2aacbba911ea8cefac1f6b21d262__6.png\n",
      "\n",
      "saved: 241b266cbba911eaa159ac1f6b21d262__23.png\n",
      "\n",
      "saved: 2403643cbba911eab96eac1f6b21d262__11.png\n",
      "saved: 244baf26bba911eaa524ac1f6b21d262__11.pngsaved: 246ee3f6bba911ea93efac1f6b21d262__26.png\n",
      "saved: 237b6dfcbba911eaa4ddac1f6b21d262__29.png\n",
      "\n",
      "saved: 22e6b68abba911eab065ac1f6b21d262__32.png\n",
      "saved: 249bcd6cbba911eabc6aac1f6b21d262__26.pngsaved: 24348ca6bba911ea87cdac1f6b21d262__9.pngsaved: 2427f018bba911eaaa56ac1f6b21d262__29.png\n",
      "\n",
      "\n",
      "saved: 24bfc97ebba911eaa159ac1f6b21d262__26.png\n",
      "saved: 2510f542bba911ea93efac1f6b21d262__29.png\n",
      "saved: 24d7cf2ebba911eab96eac1f6b21d262__13.pngsaved: 2482e73ebba911ea808bac1f6b21d262__6.png\n",
      "\n",
      "saved: 25195660bba911eaa524ac1f6b21d262__13.pngsaved: 1ff05a12bba911ea96ceac1f6b21d262__32.png\n",
      "saved: 24c1d516bba911ea8cefac1f6b21d262__8.png\n",
      "saved: 257371d6bba911eabc6aac1f6b21d262__29.png\n",
      "saved: 24b8db5abba911eabad2ac1f6b21d262__13.png\n",
      "\n",
      "saved: 2029e48abba911ea9ab1ac1f6b21d262__32.png\n",
      "saved: 259fd4a6bba911eaa159ac1f6b21d262__29.png\n",
      "saved: 251fff56bba911eaaef0ac1f6b21d262__0.pngsaved: 25dbc740bba911eab96eac1f6b21d262__23.png\n",
      "\n",
      "saved: 24d4a52ebba911eaa6afac1f6b21d262__32.pngsaved: 25f9cf24bba911eaa524ac1f6b21d262__23.png\n",
      "\n",
      "saved: 262e4164bba911eabad2ac1f6b21d262__23.pngsaved: 257c7524bba911eab065ac1f6b21d262__8.png\n",
      "\n",
      "saved: 25ed977cbba911ea808bac1f6b21d262__8.pngsaved: 26aae7f0bba911eaaef0ac1f6b21d262__33.png\n",
      "saved: 25995996bba911ea87cdac1f6b21d262__11.png\n",
      "\n",
      "saved: 26c035babba911eab96eac1f6b21d262__24.png\n",
      "saved: 26f27c64bba911eaa524ac1f6b21d262__24.pngsaved: 268adc94bba911ea9ab1ac1f6b21d262__8.pngsaved: 263c295abba911ea96ceac1f6b21d262__19.png\n",
      "\n",
      "saved: 26f4ae94bba911eabad2ac1f6b21d262__24.png\n",
      "saved: 262e8fcabba911eaa4ddac1f6b21d262__0.png\n",
      "saved: 2629b81abba911ea8cefac1f6b21d262__9.png\n",
      "\n",
      "saved: 2687383cbba911eaaa56ac1f6b21d262__0.png\n",
      "saved: 26f78312bba911eaa6afac1f6b21d262__6.png\n",
      "saved: 2696716cbba911ea93efac1f6b21d262__0.png\n",
      "saved: 27109384bba911eab065ac1f6b21d262__9.pngsaved: 27e77cf0bba911eaa4ddac1f6b21d262__32.png\n",
      "\n",
      "saved: 27948266bba911eab96eac1f6b21d262__26.pngsaved: 278abdeebba911ea87cdac1f6b21d262__12.png\n",
      "\n",
      "saved: 27b5755cbba911eaa524ac1f6b21d262__26.pngsaved: 27e6168abba911eabad2ac1f6b21d262__26.png\n",
      "saved: 2768daa8bba911eaaef0ac1f6b21d262__32.pngsaved: 26eefbfcbba911eabc6aac1f6b21d262__0.pngsaved: 27dbf0ecbba911ea9ab1ac1f6b21d262__9.png\n",
      "\n",
      "\n",
      "\n",
      "saved: 2787393abba911ea808bac1f6b21d262__9.png\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "saved: 27e99e2cbba911ea96ceac1f6b21d262__26.pngsaved: 28106e9ebba911ea8cefac1f6b21d262__10.png\n",
      "\n",
      "saved: 28618f90bba911eaa6afac1f6b21d262__12.png\n",
      "saved: 27896ee4bba911eaa159ac1f6b21d262__0.png\n",
      "saved: 28fdd1acbba911eabad2ac1f6b21d262__29.pngsaved: 28a360a0bba911eaa4ddac1f6b21d262__33.pngsaved: 288009acbba911ea93efac1f6b21d262__33.png\n",
      "\n",
      "\n",
      "saved: 290764e2bba911eaaef0ac1f6b21d262__8.png\n",
      "saved: 2830d2b0bba911eaaa56ac1f6b21d262__32.png\n",
      "saved: 290b0390bba911eabc6aac1f6b21d262__32.png\n",
      "saved: 29275b12bba911ea9ab1ac1f6b21d262__12.png\n",
      "saved: 294b5468bba911ea808bac1f6b21d262__10.pngsaved: 29b7d23cbba911eaa159ac1f6b21d262__32.png\n",
      "\n",
      "saved: 28b517b4bba911eab065ac1f6b21d262__12.pngsaved: 29f86298bba911eaaef0ac1f6b21d262__9.png\n",
      "saved: 297f2040bba911ea8cefac1f6b21d262__11.png\n",
      "\n",
      "saved: 2a0aadccbba911eaaa56ac1f6b21d262__33.pngsaved: 28e6c304bba911ea87cdac1f6b21d262__13.png\n",
      "\n",
      "saved: 29d47c34bba911eaa4ddac1f6b21d262__6.png\n",
      "saved: 2afd827cbba911eaaa56ac1f6b21d262__3.pngsaved: 29b8a5aebba911eaa6afac1f6b21d262__14.png\n",
      "saved: 2ac7f594bba911eaaef0ac1f6b21d262__11.pngsaved: 2b1dfb1abba911eaa4ddac1f6b21d262__8.png\n",
      "\n",
      "saved: 29da1888bba911ea93efac1f6b21d262__32.png\n",
      "saved: 2a9f413abba911ea808bac1f6b21d262__11.png\n",
      "\n",
      "saved: 2ba48eb4bba911eaaa56ac1f6b21d262__6.pngsaved: 2ae873d2bba911ea8cefac1f6b21d262__12.pngsaved: 2ad1fc38bba911eab065ac1f6b21d262__13.png\n",
      "\n",
      "\n",
      "saved: 2a81eb76bba911ea9ab1ac1f6b21d262__19.pngsaved: 2bb7d0aabba911eaaef0ac1f6b21d262__12.png\n",
      "saved: 2bbec978bba911eaa4ddac1f6b21d262__9.png\n",
      "saved: 2a314de2bba911eabc6aac1f6b21d262__33.png\n",
      "saved: 2a9e7b88bba911eaa159ac1f6b21d262__33.png\n",
      "\n",
      "saved: 2bce6db0bba911ea93efac1f6b21d262__3.png\n",
      "saved: 2bc87e64bba911eaa6afac1f6b21d262__19.png\n",
      "saved: 2c9f3418bba911eaa159ac1f6b21d262__3.pngsaved: 2bdf1dc2bba911ea808bac1f6b21d262__13.pngsaved: 2c92e604bba911eabc6aac1f6b21d262__3.png\n",
      "saved: 2c80ab9cbba911eaa4ddac1f6b21d262__11.png\n",
      "saved: 2b24b3f6bba911ea87cdac1f6b21d262__19.png\n",
      "saved: 2cced506bba911ea93efac1f6b21d262__8.pngsaved: 2c3b45a2bba911eaaa56ac1f6b21d262__8.png\n",
      "\n",
      "\n",
      "\n",
      "saved: 2c656ec2bba911ea8cefac1f6b21d262__13.png\n",
      "saved: 2c49ec6abba911eab065ac1f6b21d262__19.pngsaved: 2d3cb7a6bba911eaa159ac1f6b21d262__6.pngsaved: 2c8180c6bba911ea9ab1ac1f6b21d262__20.png\n",
      "\n",
      "\n",
      "saved: 2d6c322ebba911ea93efac1f6b21d262__9.pngsaved: 2d52af98bba911eabc6aac1f6b21d262__6.png\n",
      "\n",
      "saved: 2d7af610bba911eaaa56ac1f6b21d262__9.pngsaved: 2d66ad54bba911eaa4ddac1f6b21d262__12.pngsaved: 2dea611cbba911eaa159ac1f6b21d262__8.pngsaved: 2d432532bba911eaa6afac1f6b21d262__22.png\n",
      "\n",
      "saved: 2c72967ebba911eaaef0ac1f6b21d262__13.png\n",
      "\n",
      "\n",
      "saved: 2e1b511ebba911eabc6aac1f6b21d262__8.pngsaved: 2ae6ff48bba911eabad2ac1f6b21d262__0.pngsaved: 2d9b4b7cbba911ea87cdac1f6b21d262__20.png\n",
      "\n",
      "saved: 2e194dd8bba911ea93efac1f6b21d262__11.png\n",
      "\n",
      "saved: 29def204bba911eab96eac1f6b21d262__0.png\n",
      "saved: 2e7bc88cbba911eaaa56ac1f6b21d262__10.png\n",
      "saved: 2a0d43debba911eaa524ac1f6b21d262__0.pngsaved: 2d6533e8bba911ea808bac1f6b21d262__20.pngsaved: 2df787b6bba911ea9ab1ac1f6b21d262__23.pngsaved: 2e888ed2bba911eaa4ddac1f6b21d262__13.png\n",
      "\n",
      "\n",
      "saved: 2e929198bba911eaa159ac1f6b21d262__9.png\n",
      "saved: 2ebb9a20bba911eabc6aac1f6b21d262__9.png\n",
      "saved: 2dfc80febba911eab065ac1f6b21d262__20.pngsaved: 2ea5e8d8bba911eaaef0ac1f6b21d262__14.png\n",
      "\n",
      "\n",
      "saved: 2b5824cabba911ea96ceac1f6b21d262__0.png\n",
      "saved: 2f51f2aebba911eaa159ac1f6b21d262__10.png\n",
      "saved: 2f3c57f0bba911eaa4ddac1f6b21d262__19.png\n",
      "saved: 2de0920ebba911ea8cefac1f6b21d262__23.pngsaved: 2f5f1024bba911eabc6aac1f6b21d262__11.pngsaved: 2f6d0080bba911eaaef0ac1f6b21d262__20.pngsaved: 2eb85694bba911eaa6afac1f6b21d262__23.png\n",
      "\n",
      "saved: 2ee39930bba911ea93efac1f6b21d262__12.png\n",
      "\n",
      "\n",
      "saved: 2eee0d3ebba911ea87cdac1f6b21d262__23.pngsaved: 2fd7c96abba911eaa159ac1f6b21d262__11.png\n",
      "\n",
      "saved: 2f4e721ebba911ea9ab1ac1f6b21d262__26.pngsaved: 2f166752bba911eaaa56ac1f6b21d262__12.png\n",
      "saved: 30316740bba911ea93efac1f6b21d262__14.pngsaved: 2feb5958bba911eaa4ddac1f6b21d262__23.png\n",
      "saved: 3016c0c0bba911eaaef0ac1f6b21d262__21.pngsaved: 2f8a86aabba911eab065ac1f6b21d262__21.png\n",
      "\n",
      "\n",
      "\n",
      "saved: 301a3d68bba911eabc6aac1f6b21d262__12.png\n",
      "saved: 2f6a97c8bba911ea808bac1f6b21d262__23.png\n",
      "saved: 303e02debba911eaa6afac1f6b21d262__24.pngsaved: 30f10d16bba911eaaef0ac1f6b21d262__26.png\n",
      "saved: 30d8767abba911eaaa56ac1f6b21d262__13.pngsaved: 30997178bba911eaa159ac1f6b21d262__12.pngsaved: 30e961c4bba911ea93efac1f6b21d262__19.png\n",
      "saved: 30f24dacbba911eaa4ddac1f6b21d262__25.png\n",
      "\n",
      "\n",
      "\n",
      "saved: 3124b76abba911eabc6aac1f6b21d262__14.png\n",
      "saved: 301d82fcbba911ea8cefac1f6b21d262__26.pngsaved: 31843fbebba911eaaef0ac1f6b21d262__29.png\n",
      "saved: 31941ae2bba911eaa159ac1f6b21d262__13.png\n",
      "saved: 319560bebba911eaaa56ac1f6b21d262__19.pngsaved: 3099f990bba911ea87cdac1f6b21d262__24.pngsaved: 30cfe5fabba911ea9ab1ac1f6b21d262__29.png\n",
      "\n",
      "\n",
      "\n",
      "saved: 319b6ab8bba911eaa4ddac1f6b21d262__26.png\n",
      "saved: 31968e94bba911ea93efac1f6b21d262__20.png"
     ]
    }
   ],
   "source": [
    "start_time = time.time()\n",
    "pool = multiprocessing.Pool(processes = multiprocessing.cpu_count())\n",
    "pool.map(delabeler,list_of_path_tuples)\n",
    "pool.close()\n",
    "print(f'Total generation time: {time.time()-start_time} seconds')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### Cityscapes train took 6075 seconds.\n",
    "#### IDD train took ___ seconds"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
